// Admin API Service - Hour 3.3 (30 min)
// - fetchAllUsers()
// - changeUserRole(userId, newRole)
// - deactivateUser(userId)
// - getAuditLogs(query)
// - getRecentAuditLogs(limit)
// - getUserAuditLogs(userId, query)
// - getSuspiciousActivities(query)
// - updateSuspiciousActivityStatus(activityId, status, reviewNotes)
// - getUserLoginPatterns(userId)
// - detectPasswordSprayAttack()
