// Authentication API Service - Hour 1.2 (45 min)
// - signup(email, password, firstname, lastname, username, role, preferredLanguage, timezone)
// - login(email, password, rememberMe)
// - verifyEmail(token)
// - forgotPassword(email)
// - resetPassword(token, newPassword)
// - setup2fa() - GET request
// - enable2fa(code)
// - disable2fa(code)
// - verify2fa(code)
// - refreshToken(refreshToken)
// - logout(refreshToken?, sessionToken?)
// - deactivateAccount(password)
