// Admin Logic Implementation - Day 1 Afternoon Hour 3.3 (30 min)
// - fetchAllUsers()
// - handleUsersSuccess(response)
// - handleUsersError(error)
// - changeUserRole(userId, newRole)
// - deactivateUser(userId)
// - handleRoleChangeSuccess()
// - handleRoleChangeError(error)
// - handleDeactivationSuccess()
// - handleDeactivationError(error)
// - validateAdminAccess()
// - redirectToUnauthorized()
// - formatUserData(users)
// - filterUsersByRole(users, role)
// - searchUsers(users, query)
